// demo/uni-app-vite-vue3-hbuilderx-tailwindcss-v4/pages/index/index.vue
<template>
	<view class="bg-[#123456]">
		<image class="w-[120px] h-[6rem]" src="/static/logo.png"></image>
		<view class="text-[#888800]">
			<text class="title">{{title}}</text>
		</view>
		<view class="theme-mode-demo mt-4 rounded bg-white px-4 py-3 text-slate-900 system-dark:bg-slate-900 system-dark:text-slate-100 dark:bg-zinc-900 dark:text-zinc-50">
			uni-app HBuilderX Tailwind CSS v4 system dark
			<view class="theme-dark mt-2 rounded bg-white px-3 py-2 text-slate-900 dark:bg-zinc-950 dark:text-zinc-50">
				uni-app HBuilderX Tailwind CSS v4 manual dark
			</view>
		</view>
	</view>
</template>

<script>
	export default {
		data() {
			return {
				title: 'Hello'
			}
		},
		onLoad() {

		},
		methods: {

		}
	}
</script>

<style>

</style>

// demo/taro-vite-react-tailwindcss-v3/src/pages/index/index.tsx
import { View, Text } from '@tarojs/components'
import './index.scss'

export default function Index() {
  return (
    <View>
      <View className='bg-[red] flex flex-col'>
        <View className='text-[#438821] dark:text-[#ec4f4f] before:content-["11111"]'>Hello world!</View>
        <View className="text-[#3d31a4] before:content-['222']">Hello world!</View>
      </View>
      <View className='theme-mode-demo mt-4 rounded bg-white px-4 py-3 text-slate-900 system-dark:bg-slate-900 system-dark:text-slate-100 theme-dark:bg-zinc-900 theme-dark:text-zinc-50 dark:bg-zinc-900 dark:text-zinc-50'>
        Taro Vite React Tailwind CSS v3 system dark
        <View className='theme-dark mt-2 rounded bg-white px-3 py-2 text-slate-900 theme-dark:bg-zinc-950 theme-dark:text-zinc-50'>
          Taro Vite React Tailwind CSS v3 manual dark
        </View>
      </View>
      <View className='bg-[#89ab8d] flex divide-x-8 divide-solid divide-[#60d256]'>
        <View className='text-[#438821] dark:text-[#ec4f4f] before:content-["11111"]'>Hello world!</View>
        <View className="text-[#3d31a4] before:content-['222']">Hello world!</View>
      </View>
    </View>
  )
}
