// templates/taro-webpack-tailwindcss-v4/src/pages/index/sections/WorkflowSection.tsx
import { View, Text } from '@tarojs/components'
import type { WorkflowStep } from '../content'

type WorkflowSectionProps = {
  steps: WorkflowStep[]
}

export function WorkflowSection({ steps }: WorkflowSectionProps) {
  return (
    <View className='mt-[80rpx] rounded-[40rpx] border border-white/10 bg-gradient-to-br from-slate-900 to-slate-800 p-[48rpx] shadow-[0_50rpx_80rpx_rgba(0,0,0,0.35)]'>
      <Text className='text-[40rpx] font-semibold text-white'>产品迭代路线</Text>
      <Text className='mt-[8rpx] block text-[26rpx] text-slate-300'>
        从初始化到持续交付的完整流程，保持设计与工程协同。
      </Text>
      <View className='mt-[32rpx] space-y-[32rpx]'>
        {steps.map((step) => (
          <View key={step.label} className='rounded-[28rpx] bg-white/5 p-[32rpx] ring-1 ring-white/10'>
            <View className='flex items-center justify-between'>
              <Text className='text-[32rpx] font-semibold text-emerald-200'>{step.label}</Text>
              <View className='rounded-full bg-emerald-400/10 px-[20rpx] py-[10rpx] text-[24rpx] text-emerald-100'>
                <Text>Tailwind v4</Text>
              </View>
            </View>
            <Text className='mt-[12rpx] block font-mono text-[28rpx] text-white'>{step.detail}</Text>
            <Text className='mt-[8rpx] block text-[26rpx] text-slate-300'>{step.tip}</Text>
          </View>
        ))}
      </View>
    </View>
  )
}

// templates/uni-app-tailwindcss-v4/src/components/WorkflowSection.vue
<template>
  <view :class="containerClass">
    <view class="flex items-center justify-between">
      <text class="text-[30rpx] font-semibold text-slate-900">开发流程</text>
      <view :class="badgeClass">
        极速交付
      </view>
    </view>
    <view class="space-y-[22rpx]">
      <view v-for="(step, index) in steps" :key="step.title" class="flex items-start space-x-[16rpx]">
        <view class="flex flex-col items-center">
          <view :class="indexBadgeClass">
            {{ index + 1 }}
          </view>
          <view
            v-if="index !== steps.length - 1"
            :class="connectorClass"
            style="height: 80rpx"
          />
        </view>
        <view :class="cardClass">
          <text class="text-[28rpx] font-semibold text-slate-900">{{ step.title }}</text>
          <view class="mt-[8rpx] text-[24rpx] text-slate-600 leading-[1.5]">
            {{ step.desc }}
          </view>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
type FlowStep = {
  title: string
  desc: string
}

const containerClass = 'rounded-[28rpx] bg-white border border-slate-200 shadow-lg p-[24rpx] space-y-[20rpx]'
const badgeClass = 'px-[16rpx] py-[8rpx] rounded-full bg-slate-900 text-white text-[22rpx]'
const indexBadgeClass =
  'w-[36rpx] h-[36rpx] rounded-full bg-gradient-to-br from-emerald-400 to-cyan-400 text-slate-900 font-semibold flex items-center justify-center'
const connectorClass = 'flex-1 w-[6rpx] bg-gradient-to-b from-emerald-300/60 to-slate-200 rounded-full'
const cardClass = 'flex-1 bg-slate-50 border border-slate-200 rounded-[20rpx] p-[16rpx]'

defineProps<{
  steps: FlowStep[]
}>()
</script>
