// demo/taro-vite-vue3-tailwindcss-v3/src/pages/index/test.vue
<template>
  <view>
    <view class="bg-[#e24826] flex flex-col">
      <view class="text-[#438821] dark:text-[#ec4f4f] before:content-['11111'] text-[66rpx]">Tests</view>
      <view class="text-[#3d31a4] before:content-['222']">Tests</view>
    </view>
    <view class="bg-[#89ab8d] flex divide-x-8 divide-solid divide-[#60d256]">
      <view class="text-[#438821] dark:text-[#ec4f4f] before:content-['11111']">Hello world!</view>
      <view class="text-[#3d31a4] before:content-['222']">Tests</view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { useLoad } from '@tarojs/taro'

useLoad(() => {})
</script>

// demo/taro-vite-tailwindcss-v3/src/pages/index/test.tsx
import { View } from "@tarojs/components"
import { useLoad } from "@tarojs/taro"

export default function Index() {
  useLoad(() => {
    console.log('Page loaded.')
  })

  return (
    <View>
      <View className='bg-[#e24826] flex flex-col'>
        <View className='text-[#438821] dark:text-[#ec4f4f] before:content-["11111"] text-[66rpx]'>Tests</View>
        <View className='text-[#3d31a4] before:content-["222"]'>Tests</View>
      </View>
      <View className='bg-[#89ab8d] flex divide-x-8 divide-solid divide-[#60d256]'>
        <View className='text-[#438821] dark:text-[#ec4f4f] before:content-["11111"]'>Hello world!</View>
        <View className='text-[#3d31a4] before:content-["222"]'>Tests</View>
      </View>
    </View>
  )
}
