// demo/taro-webpack-vue3-tailwindcss-v4/src/pages/index/index.vue
<template>
  <view>
    <view class="bg-[#534312] text-[#fff] text-[100rpx]">
      <text>Hello Vue3!</text>
    </view>
    <view class="bg-purple-800 text-pink-200">Taro Webpack Vue3 Tailwind CSS v4</view>
    <view class="h-14 bg-gradient-to-r from-cyan-500 to-blue-500" />
    <view class="rounded-[24rpx] bg-[#123456] px-[32px] py-[18px] text-[#ffffff]">
      Share
    </view>
  </view>
</template>

<script setup lang="ts">
import { useLoad } from '@tarojs/taro'
import './index.css'

useLoad(() => {})
</script>

// demo/taro-vite-tailwindcss-v4/src/pages/index/index.tsx
import { View, Text } from '@tarojs/components'
import { useLoad } from '@tarojs/taro'
import './index.css'

export default function Index() {
  useLoad(() => {
    console.log('Page loaded.')
  })

  return (
    <View className='index'>
      <div className='h-[300px] text-[#c31d6b] bg-[#123456]'>短斤少两快点撒</div>
      <Text className='text-[55rpx] text-[#fff] bg-purple-300'>Hello world!</Text>
      <View className='h-14 bg-gradient-to-r from-cyan-500 to-blue-500'></View>
    </View>
  )
}
