// templates/uni-app-tailwindcss-v4/src/components/HeroSection.vue
<template>
  <view :class="containerClass">
    <view :class="emeraldBlobClass" />
    <view :class="cyanBlobClass" />
    <view :class="outlineClass" />

    <view class="relative flex flex-col space-y-[24rpx]">
      <view class="flex flex-wrap items-center gap-[12rpx]">
        <view :class="primaryBadgeClass">
          Tailwind CSS 4 · Uni App
        </view>
        <view :class="secondaryBadgeClass">
          微信小程序 Demo
        </view>
      </view>

      <view class="space-y-[12rpx]">
        <text class="text-[56rpx] font-extrabold leading-[1.1] tracking-tight">
          {{ title }}
        </text>
        <text class="text-[28rpx] text-white/70 leading-[1.5]">
          {{ subtitle }}
        </text>
      </view>

      <view class="flex flex-wrap gap-[12rpx]">
        <view
          v-for="item in highlights"
          :key="item"
          :class="highlightChipClass"
        >
          {{ item }}
        </view>
      </view>

      <view class="flex flex-wrap items-center gap-[16rpx]">
        <IceButton :custom-class="ctaClass">
          即刻上手
        </IceButton>
        <button :class="ghostButtonClass">
          查看设计思路
        </button>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import IceButton from '@/components/IceButton.vue'

const containerClass =
  'relative overflow-hidden rounded-[32rpx] bg-gradient-to-br from-slate-900 via-slate-800 to-black text-white p-[32rpx] shadow-2xl border border-white/10'
const emeraldBlobClass =
  'absolute -left-[120rpx] -top-[120rpx] w-[300rpx] h-[300rpx] bg-emerald-500/20 blur-3xl pointer-events-none'
const cyanBlobClass =
  'absolute right-[-60rpx] top-[-40rpx] w-[260rpx] h-[260rpx] bg-cyan-400/15 blur-3xl pointer-events-none'
const outlineClass = 'absolute inset-0 border border-white/5 rounded-[32rpx] pointer-events-none'
const primaryBadgeClass = 'px-[18rpx] py-[10rpx] rounded-full bg-white/10 border border-white/20 text-[24rpx]'
const secondaryBadgeClass =
  'px-[18rpx] py-[10rpx] rounded-full bg-emerald-400/20 text-emerald-100 text-[24rpx] border border-emerald-300/40'
const highlightChipClass =
  'px-[16rpx] py-[12rpx] rounded-[16rpx] bg-white/5 border border-white/10 text-[24rpx] text-white/80'
const ctaClass =
  'bg-emerald-400 text-slate-900 px-[28rpx] py-[16rpx] rounded-[18rpx] shadow-lg shadow-emerald-500/30 border-emerald-300 text-[28rpx]'
const ghostButtonClass =
  'px-[24rpx] py-[14rpx] rounded-[16rpx] border border-white/30 text-white/80 bg-white/10 text-[26rpx]'

defineProps<{
  title: string
  subtitle: string
  highlights: string[]
}>()
</script>

// templates/taro-webpack-tailwindcss-v4/src/pages/index/sections/HeroSection.tsx
import { View, Text } from '@tarojs/components'

type HeroSectionProps = {
  quickActions: string[]
}

export function HeroSection({ quickActions }: HeroSectionProps) {
  return (
    <View className='rounded-[48rpx] border border-white/10 bg-gradient-to-b from-emerald-400/15 via-teal-400/5 to-slate-900 p-[64rpx] shadow-[0_60rpx_120rpx_rgba(20,184,166,0.25)]'>
      <View className='flex items-center gap-[16rpx]'>
        <View className='rounded-full bg-emerald-400/15 px-[24rpx] py-[12rpx] text-[26rpx] text-emerald-100 ring-1 ring-emerald-300/40'>
          <Text className='font-semibold tracking-[4rpx]'>Tailwind 4 • Multi-end</Text>
        </View>
        <View className='rounded-full bg-white/10 px-[20rpx] py-[10rpx] text-[24rpx] text-white/80'>
          <Text>Design token + CSS 变量一体化</Text>
        </View>
      </View>

      <View className='mt-[32rpx] text-[72rpx] font-semibold leading-tight text-white'>
        <Text>打造跨端体验一致的 Taro 产品主页</Text>
      </View>

      <View className='mt-[24rpx] text-[30rpx] leading-relaxed text-slate-200'>
        <Text>
          通过 tailwindcss@4 的原子化语法，即可在小程序、H5、甚至多端容器中维持一致的布局、间距与交互动效。
          下面的示例展示了几种常用信息模块，帮助你快速搭建首页与营销落地页。
        </Text>
      </View>

      <View className='mt-[36rpx] grid grid-cols-2 gap-[20rpx] rounded-[32rpx] bg-white/5 p-[24rpx] backdrop-blur-md'>
        <View className='rounded-[24rpx] bg-gradient-to-r from-white/10 to-white/5 p-[20rpx]'>
          <Text className='text-[28rpx] font-semibold text-emerald-200'>更轻的 CLI</Text>
          <Text className='mt-[8rpx] block text-[26rpx] text-slate-200'>无配置即可生成样式，JIT 秒级响应。</Text>
        </View>
        <View className='rounded-[24rpx] border border-white/10 bg-slate-950/50 p-[20rpx] shadow-inner shadow-black/30'>
          <Text className='text-[28rpx] font-semibold text-emerald-200'>统一设计 token</Text>
          <Text className='mt-[8rpx] block text-[26rpx] text-slate-200'>颜色、圆角、阴影全部抽象为 CSS 变量。</Text>
        </View>
      </View>

      <View className='mt-[48rpx] flex flex-wrap gap-[24rpx]'>
        {quickActions.map((action) => (
          <View
            key={action}
            className='rounded-full border border-emerald-300/60 bg-emerald-400/10 px-[48rpx] py-[18rpx] text-[28rpx] font-medium text-emerald-100'
          >
            <Text className='font-mono tracking-[4rpx]'>{action}</Text>
          </View>
        ))}
      </View>
    </View>
  )
}
