// apps/vue-app/src/features/home/GithubLink.vue
<script setup lang="ts">
import { ArrowUpRight, Github } from 'lucide-vue-next'

import { Button } from '@/components/ui/button'

const props = withDefaults(defineProps<{ href?: string }>(), {
  href: 'https://github.com/sonofmagic/weapp-tailwindcss',
})
</script>

<template>
  <Button
    as="a"
    variant="outline"
    size="sm"
    class="gap-2"
    :href="props.href"
    target="_blank"
    rel="noreferrer"
  >
    <Github class="h-4 w-4" />
    GitHub
    <ArrowUpRight class="h-3 w-3" />
  </Button>
</template>

// apps/react-app/src/components/github-link.tsx
import { Button } from "@/components/ui/button"
import { ArrowUpRightIcon, GithubIcon } from "@/features/home/icons"

type GithubLinkProps = {
  href?: string
}

export function GithubLink({ href = "https://github.com/sonofmagic/weapp-tailwindcss" }: GithubLinkProps) {
  return (
    <Button variant="outline" size="sm" className="gap-2" asChild>
      <a href={href} target="_blank" rel="noreferrer">
        <GithubIcon className="size-4" />
        GitHub
        <ArrowUpRightIcon className="size-3" />
      </a>
    </Button>
  )
}
