// demo/taro-vite-react-tailwindcss-v3/src/pages/index/index.tsx
import { View, Text } from '@tarojs/components'
import './index.scss'
import { Button as NutButton } from '@nutui/nutui-react-taro'

export default function Index() {
  return (
    <View>
      <View className='bg-[red] flex flex-col'>
        <View className='text-[#438821] dark:text-[#ec4f4f] before:content-["11111"]'>Hello world!</View>
        <View className="text-[#3d31a4] before:content-['222']">Hello world!</View>
      </View>
      <View className='weapp-tw-nutui-react-demo mt-4'>
        <NutButton type='primary'>NutUI React Button</NutButton>
      </View>
      <View className='theme-mode-demo mt-4 rounded bg-white px-4 py-3 text-slate-900 system-dark:bg-slate-900 system-dark:text-slate-100 theme-dark:bg-zinc-900 theme-dark:text-zinc-50 dark:bg-zinc-900 dark:text-zinc-50'>
        Taro Vite React Tailwind CSS v3 system dark
        <View className='theme-dark mt-2 rounded bg-white px-3 py-2 text-slate-900 theme-dark:bg-zinc-950 theme-dark:text-zinc-50'>
          Taro Vite React Tailwind CSS v3 manual dark
        </View>
      </View>
      <View className='bg-[#89ab8d] flex divide-x-8 divide-solid divide-[#60d256]'>
        <View className='text-[#438821] dark:text-[#ec4f4f] before:content-["11111"]'>Hello world!</View>
        <View className="text-[#3d31a4] before:content-['222']">Hello world!</View>
      </View>
    </View>
  )
}

// demo/taro-webpack-vue3-tailwindcss-v3/src/pages/index/index.vue
<template>
  <view>
    <view class="relative h-12 w-12 before:absolute before:inset-0 before:border-2 before:border-[#4bd650] rounded-[20rpx] before:rounded-[20rpx]" />
    <view class="shadow-md">shadow-md</view>
    <view class="form-box py-[62px] rotate-45 px-[95px] bg-sky-500/80 dark:bg-[#123456]">
      Taro Webpack Vue3 Tailwind CSS v3
    </view>
    <view class="weapp-tw-nutui-vue-demo mt-4">
      <nut-button type="primary">NutUI Vue Button</nut-button>
    </view>
    <view class="theme-mode-demo mt-4 rounded bg-white px-4 py-3 text-slate-900 system-dark:bg-slate-900 system-dark:text-slate-100 theme-dark:bg-zinc-900 theme-dark:text-zinc-50 dark:bg-zinc-900 dark:text-zinc-50">
      Taro Webpack Vue3 Tailwind CSS v3 system dark
      <view class="theme-dark mt-2 rounded bg-white px-3 py-2 text-slate-900 theme-dark:bg-zinc-950 theme-dark:text-zinc-50">
        Taro Webpack Vue3 Tailwind CSS v3 manual dark
      </view>
    </view>
    <view :class="dynamicClass">dynamic class</view>
    <view class="space-y-[1.6rem] text-[16px] w-[200%]">
      <view class="w-[300rpx] text-black text-opacity-[0.19]">w-[300rpx] text-black text-opacity-[0.19]</view>
      <view class="min-w-[300rpx] max-h-[100px] text-[20px] leading-[0.9]">min-w-[300rpx] max-h-[100px]</view>
      <view class="grid grid-cols-3 divide-x-[10px] divide-[#010101] divide-solid">
        <view>1</view>
        <view>2</view>
        <view>3</view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useLoad } from '@tarojs/taro'

const dynamicClass = computed(() => 'bg-[#123456] text-[#ffffff] p-[20px]')

useLoad(() => {})
</script>

<style lang="scss">
.test {
  @apply flex items-center justify-center h-[100px] w-[100px] rounded-[40px] bg-[#123456] bg-opacity-[0.54] text-[#ffffff] #{!important};
}

.aspect-w-16 > * {
  color: red;
}

.a {
  color: green;
}

.b {
  color: yellow;
}
</style>
